/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.10.3
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client.api';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client.api';
    


// Services

export interface MyServiceDef {
    greeting: (name: string, callParams: CallParams$$<'name'>) => string | Promise<string>;
}
export function registerMyService(service: MyServiceDef): void;
export function registerMyService(serviceId: string, service: MyServiceDef): void;
export function registerMyService(peer: IFluenceClient$$, service: MyServiceDef): void;
export function registerMyService(peer: IFluenceClient$$, serviceId: string, service: MyServiceDef): void;
       

export function registerMyService(...args: any) {
    registerService$$(
        args,
        {
    "defaultServiceId" : "myService",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "greeting" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "name" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions
 

export function makeKey(
    name: string,
    workerId: string,
    hostId: string,
    config?: {ttl?: number}
): Promise<string>;

export function makeKey(
    peer: IFluenceClient$$,
    name: string,
    workerId: string,
    hostId: string,
    config?: {ttl?: number}
): Promise<string>;

export function makeKey(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                            (call %init_peer_id% ("getDataSrv" "name") [] name)
                           )
                           (call %init_peer_id% ("getDataSrv" "workerId") [] workerId)
                          )
                          (call %init_peer_id% ("getDataSrv" "hostId") [] hostId)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (call hostId ("op" "noop") [])
                       )
                       (xor
                        (seq
                         (seq
                          (call workerId ("myService" "greeting") [name] results)
                          (call hostId ("op" "noop") [])
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (seq
                          (call hostId ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [results])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
    return callFunction$$(
        args,
        {
    "functionName" : "makeKey",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "name" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "workerId" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "hostId" : {
                    "tag" : "scalar",
                    "name" : "string"
                }
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "scalar",
                    "name" : "string"
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

/* eslint-enable */